name: Run Postman Tests

on:
  push:
    branches: [ main ]

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Postman collection
        run: |
          newman run "4-lesson for postman.postman_collection.json" \
          -r htmlextra --reporter-htmlextra-export "newman-report.html"
